"""
SpeakBetter Local — Topic Generator
500+ predefined speaking topics across 5 categories.
"""

import random

TOPICS = {
    "technical": [
        # ── Databases & Storage ──
        "Explain how a database index improves query performance.",
        "Describe the difference between REST and GraphQL APIs.",
        "What is the difference between SQL and NoSQL databases?",
        "How does database sharding work and when would you use it?",
        "Explain the ACID properties of database transactions.",
        "What is a materialized view and when is it useful?",
        "Describe how database replication ensures high availability.",
        "What is the difference between a B-tree and an LSM-tree index?",
        "Explain how connection pooling improves database performance.",
        "What is eventual consistency and how does it differ from strong consistency?",
        "Describe how a key-value store differs from a document database.",
        "What is a write-ahead log and why do databases use it?",
        "Explain how database normalization prevents data anomalies.",
        "When would you choose denormalization over normalization?",
        "How does a column-oriented database differ from a row-oriented one?",
        "What is the purpose of database partitioning?",
        "Explain how optimistic locking works in concurrent systems.",
        "Describe the concept of a distributed transaction.",
        "What are the trade-offs of using an in-memory database like Redis?",
        "How does a graph database model relationships differently?",
        # ── Networking & Protocols ──
        "How does HTTPS keep communication secure?",
        "Explain how DNS resolution works when you type a URL.",
        "What is WebSocket and how does it differ from HTTP?",
        "How does TCP ensure reliable data delivery?",
        "Describe how a VPN works to secure internet traffic.",
        "What is the difference between HTTP/1.1, HTTP/2, and HTTP/3?",
        "Explain how a reverse proxy works and when to use one.",
        "What is gRPC and how does it compare to REST?",
        "Describe how TLS handshake establishes a secure connection.",
        "What is the purpose of ARP in networking?",
        "How does NAT work in home routers?",
        "Explain the difference between TCP and UDP with use cases.",
        "What is a content delivery network and how does it improve speed?",
        "Describe how IPv6 addresses the limitations of IPv4.",
        "What is CORS and why does it exist?",
        "How does server-sent events differ from WebSockets?",
        "Explain how multicast differs from unicast and broadcast.",
        "What is the OSI model and why is it useful for debugging?",
        "Describe how QUIC protocol improves upon TCP.",
        "What is a proxy server and what are its common use cases?",
        # ── System Design & Architecture ──
        "Describe the concept of microservices architecture.",
        "Explain the concept of eventual consistency in distributed systems.",
        "How does a load balancer distribute traffic?",
        "Describe the purpose of a message queue in system design.",
        "Explain the CAP theorem and its implications.",
        "What is containerization and why is Docker popular?",
        "Explain the concept of serverless computing.",
        "How does rate limiting protect an API?",
        "Describe the difference between authentication and authorization.",
        "What is the role of an ORM in backend development?",
        "How does caching improve application performance?",
        "Explain how circuit breakers prevent cascade failures.",
        "What is event-driven architecture and when is it appropriate?",
        "Describe the strangler fig pattern for migrating legacy systems.",
        "How does blue-green deployment reduce downtime?",
        "What is the saga pattern for distributed transactions?",
        "Explain how an API gateway centralizes cross-cutting concerns.",
        "What is back-pressure and why does it matter in streaming systems?",
        "Describe how service mesh tools like Istio work.",
        "What is CQRS and when would you apply it?",
        "How does the sidecar pattern work in microservices?",
        "Explain the difference between vertical and horizontal scaling.",
        "What is the bulkhead pattern in system resilience?",
        "Describe how feature flags enable safe deployments.",
        "What is a dead letter queue and when is it used?",
        "How does an event sourcing system differ from traditional CRUD?",
        # ── DevOps & CI/CD ──
        "What is CI/CD and why does it matter?",
        "Describe how version control systems like Git work.",
        "What is infrastructure as code and why is it important?",
        "How does a container orchestrator like Kubernetes work?",
        "Explain the purpose of a service discovery mechanism.",
        "What is observability and how does it differ from monitoring?",
        "Describe the role of Terraform in infrastructure management.",
        "How do you implement zero-downtime deployments?",
        "What is GitOps and how does it work?",
        "Explain the difference between containers and virtual machines.",
        "What is a canary deployment strategy?",
        "How does log aggregation help in debugging distributed systems?",
        "Describe the purpose of health checks in production systems.",
        "What is chaos engineering and why would you practice it?",
        "How do secrets management tools like Vault work?",
        # ── Security ──
        "Explain how OAuth 2.0 authorization flow works.",
        "What is cross-site scripting and how do you prevent it?",
        "Describe how SQL injection attacks work.",
        "What is a JWT token and how is it used for authentication?",
        "Explain the difference between symmetric and asymmetric encryption.",
        "What is a man-in-the-middle attack and how is it prevented?",
        "How does two-factor authentication improve security?",
        "Describe the principle of least privilege in security.",
        "What is CSRF and how do web frameworks protect against it?",
        "How does hashing differ from encryption?",
        "What is a zero-trust security model?",
        "Explain how certificate pinning works in mobile apps.",
        "Describe how rate limiting prevents brute-force attacks.",
        "What is content security policy and why is it important?",
        "How do you securely store passwords in a database?",
    ],
    "abstract": [
        # ── Technology & Humanity ──
        "Is technology making us more or less connected as humans?",
        "Can artificial intelligence ever be truly creative?",
        "How does social media reshape our understanding of community?",
        "Will technology eventually eliminate the need for physical offices?",
        "How does constant access to information change how we learn?",
        "Is digital minimalism a realistic lifestyle in the modern world?",
        "How does automation change the meaning of human work?",
        "Can technology solve problems it created in the first place?",
        "How does virtual reality blur the line between experience and simulation?",
        "Will human memory become less important as external storage grows?",
        "Is algorithmic personalization expanding or narrowing our worldview?",
        "How does technology affect our ability to be present in the moment?",
        "Can a digital identity ever accurately represent who we are?",
        "How does immediacy culture affect our patience and attention span?",
        "Will future generations value privacy differently than we do?",
        "How does access to AI tools change the definition of expertise?",
        "Is the metaverse a natural evolution or a distraction from reality?",
        "How does technology change our relationship with nature?",
        "Can technology preserve culture or does it homogenize it?",
        "How does the internet change the way stories are told?",
        # ── Philosophy & Knowledge ──
        "What does it mean to truly understand something?",
        "Is there a difference between intelligence and wisdom?",
        "Is complete objectivity possible in any field?",
        "What is the difference between knowledge and information?",
        "What makes something beautiful?",
        "Is human nature fundamentally cooperative or competitive?",
        "What is the relationship between freedom and responsibility?",
        "What does it mean to live a meaningful life?",
        "How does perspective change the meaning of an event?",
        "Can logic alone resolve all moral dilemmas?",
        "What is the relationship between doubt and knowledge?",
        "Is simplicity a sign of understanding or oversimplification?",
        "How do we distinguish opinion from genuine insight?",
        "What is the value of asking questions that have no clear answer?",
        "Is truth absolute or always relative to context?",
        "How does certainty become a barrier to learning?",
        "What is the role of contradiction in advancing knowledge?",
        "Can you truly know yourself or is self-knowledge always partial?",
        "What is the difference between understanding and memorization?",
        "How does the observer change what is being observed?",
        # ── Mind & Identity ──
        "What is the relationship between memory and identity?",
        "Can empathy be taught or is it innate?",
        "How does language shape the way we think?",
        "How does culture influence the way we solve problems?",
        "How does the concept of time affect decision making?",
        "Can a machine ever have consciousness?",
        "How do we form our sense of self and how does it change?",
        "What role does intuition play in rational decision-making?",
        "How does sleep affect the way we think and create?",
        "Is personality fixed or constantly changing?",
        "How does bilingualism change the structure of thought?",
        "What is the relationship between emotion and rationality?",
        "How does fear shape our beliefs more than evidence does?",
        "Is awareness of cognitive biases enough to overcome them?",
        "How does the illusion of control affect our risk assessment?",
        "What is the relationship between creativity and constraint?",
        "How does nostalgia alter our perception of the past?",
        "What role does discomfort play in personal transformation?",
        "How does isolation change the way we think and feel?",
        "Is free will real or an elaborate illusion?",
        # ── Society & Purpose ──
        "What role does failure play in personal growth?",
        "How do you define progress in a society?",
        "What is the value of boredom in a hyper-connected world?",
        "How does gratitude change our relationship to what we have?",
        "Is ambition always a positive trait?",
        "What is the cost of always optimizing for efficiency?",
        "How does comparison with others shape our self-worth?",
        "What is the difference between happiness and fulfillment?",
        "How does the pursuit of perfection hold us back?",
        "What is the role of ritual and routine in human life?",
        "How does forgiveness benefit the person who forgives?",
        "Is competition necessary for innovation?",
        "What is the relationship between comfort and growth?",
        "How does privilege invisibly shape our worldview?",
        "What is the value of generosity beyond its effect on others?",
        "How does scarcity thinking affect decision-making?",
        "Is there a point where self-improvement becomes counterproductive?",
        "How does the fear of missing out distort our priorities?",
        "What does it mean to be truly independent?",
        "How does the way we define success shape our life choices?",
        # ── Creativity & Exploration ──
        "Where does creativity come from and can it be cultivated?",
        "What is the relationship between play and innovation?",
        "How does cross-disciplinary thinking lead to breakthroughs?",
        "Is original thought possible or is everything derivative?",
        "How does constraints-driven creativity differ from open-ended creativity?",
        "What is the role of solitude in creative work?",
        "How does exposure to different cultures enhance creativity?",
        "Is there a connection between madness and genius?",
        "How does the act of teaching deepen our own understanding?",
        "What can we learn from civilizations that no longer exist?",
    ],
    "opinion": [
        # ── Education & Learning ──
        "Should coding be taught as a mandatory subject in schools?",
        "Is a university degree still necessary for a successful career?",
        "Is standardized testing a good measure of student ability?",
        "Should schools focus more on critical thinking than memorization?",
        "Is online learning as effective as in-person education?",
        "Should students specialize earlier or have a broader education?",
        "Is homework beneficial or does it cause more harm than good?",
        "Should financial literacy be a required course in high school?",
        "Is the grading system an accurate reflection of learning?",
        "Should AI tutors replace human teachers for some subjects?",
        "Is lifelong learning a luxury or a necessity in the modern economy?",
        "Should universities be free for all students?",
        "Is rote learning ever valuable or always inferior to understanding?",
        "Should schools teach meditation and emotional regulation?",
        "Is the traditional classroom model outdated?",
        "Should apprenticeships be considered equal to college degrees?",
        "Is peer learning more effective than lecture-based learning?",
        "Should exams be open-book in the age of information access?",
        "Is the pursuit of multiple degrees a sign of growth or delay?",
        "Should educational curricula be standardized globally?",
        # ── Technology & Society ──
        "Should social media platforms be regulated by governments?",
        "Should companies be required to open-source their AI models?",
        "Should there be limits on free speech online?",
        "Should autonomous vehicles be allowed on all roads?",
        "Should tech companies be broken up to prevent monopolies?",
        "Is social media a net positive or net negative for mental health?",
        "Should governments ban facial recognition technology?",
        "Is data privacy a human right?",
        "Should algorithms that affect people be explainable by law?",
        "Is end-to-end encryption a security measure or a shield for criminals?",
        "Should children under 16 be banned from social media?",
        "Is planned obsolescence in tech products ethical?",
        "Should deepfakes be criminalized?",
        "Is screen time inherently harmful or is it about content quality?",
        "Should internet access be classified as a basic utility?",
        "Is it ethical to develop autonomous weapons?",
        "Should tech workers be held personally accountable for harmful products?",
        "Is the attention economy sustainable?",
        "Should there be a digital bill of rights?",
        "Is technological unemployment an inevitable crisis or a solvable challenge?",
        # ── Work & Economy ──
        "Is remote work better than working from an office?",
        "Is the gig economy good or bad for workers?",
        "Should the four-day work week become standard?",
        "Should countries adopt universal basic income?",
        "Is it better to be a specialist or a generalist?",
        "Should minimum wage be a living wage?",
        "Is hustle culture productive or destructive?",
        "Should companies mandate professional development time?",
        "Is working long hours a sign of dedication or poor management?",
        "Should salary transparency be required by law?",
        "Is job hopping beneficial or harmful to career growth?",
        "Should companies offer unlimited vacation?",
        "Is workplace loyalty still a valuable trait?",
        "Should employees own shares in the company they work for?",
        "Is the 9-to-5 work model still relevant?",
        "Should parental leave be equal for both parents?",
        "Is networking more important than skill for career advancement?",
        "Should companies be required to disclose their pay gap data?",
        "Is passion for work overrated as career advice?",
        "Should retirement age be abolished?",
        # ── Ethics & Governance ──
        "Is meritocracy a realistic or idealistic concept?",
        "Should voting be mandatory in democratic countries?",
        "Is it ethical to use animals for scientific research?",
        "Is privacy more important than security?",
        "Should billionaires exist in a fair society?",
        "Should governments invest more in space exploration or ocean research?",
        "Is cancel culture a form of accountability or mob justice?",
        "Should genetic engineering of humans be permitted?",
        "Is censorship ever justified in a democracy?",
        "Should organ donation be opt-out instead of opt-in?",
        "Is civil disobedience justified when laws are unjust?",
        "Should all drugs be decriminalized?",
        "Is globalization making the world better or worse?",
        "Should the death penalty be abolished worldwide?",
        "Is it ethical to colonize other planets?",
        "Should corporations have the same rights as individuals?",
        "Is altruism truly selfless or always self-serving?",
        "Should wealthy nations accept more refugees?",
        "Is direct democracy feasible with modern technology?",
        "Should cultural heritage sites be owned by nations or humanity?",
        # ── Environment & Health ──
        "Should single-use plastics be banned entirely?",
        "Is nuclear energy the most practical path to carbon neutrality?",
        "Should meat consumption be taxed for environmental reasons?",
        "Is telecommuting a meaningful climate change strategy?",
        "Should individuals or corporations bear more responsibility for emissions?",
        "Is fast fashion an ethical industry?",
        "Should all new buildings be required to have solar panels?",
        "Is mental health as important as physical health in healthcare?",
        "Should health insurance be universal and government-provided?",
        "Is preventive care more cost-effective than reactive treatment?",
    ],
    "storytelling": [
        # ── Self-Discovery ──
        "Describe a moment when you learned something unexpected about yourself.",
        "Tell the story of a decision that changed the direction of your life.",
        "Describe a moment when you realized your perspective was wrong.",
        "Tell the story of a time you discovered a hidden talent.",
        "Describe an experience that fundamentally changed your values.",
        "Tell the story of the hardest conversation you ever had with yourself.",
        "Describe a time when you surprised yourself with your own courage.",
        "Tell the story of a belief you held strongly and then abandoned.",
        "Describe a moment of quiet realization that changed everything.",
        "Tell the story of how you learned to accept a weakness.",
        "Describe a time when you had to redefine success for yourself.",
        "Tell the story of a risk you took that paid off unexpectedly.",
        "Describe a moment when silence taught you more than words.",
        "Tell the story of the first time you felt truly confident.",
        "Describe a time when you chose the harder right over the easier wrong.",
        "Tell the story of how a small habit transformed your daily life.",
        "Describe a moment of clarity that came after a long period of confusion.",
        "Tell the story of learning to say no and how it changed things.",
        "Describe a time when being alone helped you grow.",
        "Tell the story of how you overcame self-doubt in a critical moment.",
        # ── Challenges & Growth ──
        "Describe a challenge you overcame that you are proud of.",
        "Tell the story of a time when you failed and what you learned from it.",
        "Tell the story of a project that did not go as planned.",
        "Describe an experience that taught you about patience.",
        "Describe a situation where you had to make a tough ethical choice.",
        "Tell the story of how you solved a difficult problem creatively.",
        "Describe a time when everything went wrong but it turned out well.",
        "Tell the story of the biggest obstacle in your career and how you overcame it.",
        "Describe a time when you had to start completely from scratch.",
        "Tell the story of a time when persistence finally paid off.",
        "Describe a moment when you almost gave up but didn't.",
        "Tell the story of the most difficult feedback you ever received.",
        "Describe a time when a deadline seemed impossible but you met it.",
        "Tell the story of a conflict that made a relationship stronger.",
        "Describe an experience that taught you about resilience.",
        "Tell the story of a time you had to adapt quickly to a new situation.",
        "Describe a failure that led directly to a later success.",
        "Tell the story of the most stressful week of your life and how you handled it.",
        "Describe a time when you learned an important lesson the hard way.",
        "Tell the story of how a setback became a turning point.",
        # ── People & Relationships ──
        "Describe a time when you had to work with someone very different from you.",
        "Describe a person who had a significant impact on your thinking.",
        "Tell the story of the best advice you ever received.",
        "Tell the story of a time when teamwork made a real difference.",
        "Tell the story of a time you had to persuade someone of your idea.",
        "Describe a mentor who shaped who you are today.",
        "Tell the story of a friendship that changed your worldview.",
        "Describe a time when you had to lead people through uncertainty.",
        "Tell the story of a miscommunication that taught you a lesson.",
        "Describe a time when empathy helped you solve a problem.",
        "Tell the story of someone who inspired you to be better.",
        "Describe a moment when trust was broken and how you dealt with it.",
        "Tell the story of a collaboration that produced something unexpected.",
        "Describe a time when cultural differences enriched an experience.",
        "Tell the story of learning something important from a child.",
        "Describe a moment when a stranger's kindness changed your day.",
        "Tell the story of a teacher who made a lasting impression.",
        "Describe a time when you had to deliver bad news to someone.",
        "Tell the story of reconnecting with someone after a long time.",
        "Describe a relationship that taught you about boundaries.",
        # ── Experiences & Adventures ──
        "Tell the story of your most memorable travel experience.",
        "Describe your first experience with technology.",
        "Tell the story of a time you stepped outside your comfort zone.",
        "Tell the story of a tradition that is important to you.",
        "Tell the story of how you got interested in your current field.",
        "Describe a time when you had to think on your feet.",
        "Describe a place that feels like home even though it's not where you live.",
        "Tell the story of the most interesting person you've ever met.",
        "Describe a cultural event that left a lasting impression on you.",
        "Tell the story of a book, movie, or song that changed your perspective.",
        "Describe a time when nature taught you something about life.",
        "Tell the story of your most unconventional learning experience.",
        "Describe a moment when food brought people together.",
        "Tell the story of a hobby that became more than just a hobby.",
        "Describe your experience learning something completely new as an adult.",
        "Tell the story of a spontaneous decision that led somewhere great.",
        "Describe a time when you witnessed something truly remarkable.",
        "Tell the story of a family tradition and what it means to you.",
        "Describe your most challenging physical experience and what it taught you.",
        "Tell the story of a day that unfolded completely differently than expected.",
        # ── Hypothetical & Creative ──
        "Tell the story of what your life might look like in ten years.",
        "Describe a perfect day from start to finish as you imagine it.",
        "Tell the story of a historical event from the perspective of an ordinary person.",
        "Describe what advice you would give your younger self.",
        "Tell the story of how you would spend a year with no obligations.",
        "Describe the world as you think it will look in fifty years.",
        "Tell the story of a superpower you would choose and why.",
        "Describe a city you would design if you could start from scratch.",
        "Tell the story of a conversation you wish you could have with anyone in history.",
        "Describe what you would teach if you had to give a masterclass on one topic.",
    ],
    "interview": [
        # ── Behavioral ──
        "Walk me through your approach to learning a new technology.",
        "How do you handle disagreements within a team?",
        "Describe your process for debugging a complex issue.",
        "How do you prioritize tasks when everything feels urgent?",
        "What is your approach to giving and receiving feedback?",
        "Describe a time you had to explain a complex concept to a non-technical person.",
        "How do you handle a situation where you do not know the answer?",
        "How do you handle stress and pressure at work?",
        "What is a skill you are currently trying to improve and how?",
        "Describe your approach to working on tasks you find uninteresting.",
        "Tell me about a time when you had to make a decision with incomplete information.",
        "Describe a situation where you had to balance speed with quality.",
        "How do you approach admitting and recovering from a mistake at work?",
        "Tell me about a time you went above and beyond your job description.",
        "Describe a situation where you had to work under a difficult manager.",
        "How do you handle receiving criticism you disagree with?",
        "Tell me about a time you had to resolve a conflict between team members.",
        "Describe how you handle working on tasks outside your area of expertise.",
        "How do you respond when a project's scope changes significantly mid-way?",
        "Tell me about a time you had to push back on a stakeholder request.",
        # ── Leadership & Communication ──
        "What qualities do you think make a great team leader?",
        "Describe how you would mentor a junior team member.",
        "How do you build trust with new colleagues?",
        "What motivates you to do your best work?",
        "How do you stay current with developments in your field?",
        "How do you ensure everyone on the team has a voice?",
        "Describe your approach to delegating tasks effectively.",
        "How do you communicate bad news to your team or stakeholders?",
        "What is your philosophy on giving autonomy versus oversight?",
        "How do you foster a culture of continuous improvement?",
        "Describe how you handle a team member who is underperforming.",
        "How do you balance being approachable and maintaining authority?",
        "What is your approach to running effective meetings?",
        "How do you handle a situation where your team disagrees with your direction?",
        "Describe how you celebrate team successes.",
        "How do you adapt your communication style for different audiences?",
        "What is your approach to cross-functional collaboration?",
        "How do you support team members during high-stress periods?",
        "Describe how you build alignment on a team with diverse opinions.",
        "How do you maintain team morale during long or difficult projects?",
        # ── Technical Decision Making ──
        "How do you evaluate trade-offs when making technical decisions?",
        "What is your strategy for maintaining code quality in a fast-paced environment?",
        "How do you decide when something is good enough to ship?",
        "Describe your ideal work environment and why.",
        "How do you approach a project with ambiguous requirements?",
        "How do you evaluate whether to build or buy a solution?",
        "Describe your process for conducting a technical code review.",
        "How do you balance technical debt with feature development?",
        "What is your approach to choosing between competing technologies?",
        "How do you define and track meaningful engineering metrics?",
        "Describe how you approach capacity planning for a growing system.",
        "How do you ensure backward compatibility when making changes?",
        "What is your strategy for migrating from a legacy system?",
        "How do you approach writing documentation for your code?",
        "Describe your process for estimating how long a task will take.",
        "How do you handle a production incident step by step?",
        "What is your approach to testing complex distributed systems?",
        "How do you decide what to automate and what to do manually?",
        "Describe how you would architect a system from scratch for a new product.",
        "How do you stay productive on days when motivation is low?",
        # ── Problem Solving & Strategy ──
        "How do you approach a completely unfamiliar problem domain?",
        "Describe how you break down large, complex problems into manageable pieces.",
        "What is your process for root cause analysis?",
        "How do you validate assumptions before investing significant effort?",
        "Describe a framework you use for making difficult decisions.",
        "How do you handle competing priorities from multiple stakeholders?",
        "What is your approach to identifying and mitigating risks in a project?",
        "How do you ensure alignment between business goals and technical decisions?",
        "Describe how you handle a project that is falling behind schedule.",
        "How do you know when to stop iterating and move on?",
        "What is your approach to gathering requirements from non-technical users?",
        "How do you distinguish between essential and nice-to-have features?",
        "Describe your process for evaluating the success of a completed project.",
        "How do you handle scope creep in a project?",
        "What is your approach to building a minimum viable product?",
        "How do you make decisions when the data is ambiguous or missing?",
        "Describe how you prepare for a high-stakes presentation or demo.",
        "How do you approach long-term strategic planning for a codebase?",
        "What is your process for onboarding onto a new project quickly?",
        "How do you manage your own professional development alongside project work?",
        # ── Situational ──
        "How would you handle joining a team with low morale?",
        "What would you do if you inherited a codebase with no documentation?",
        "How would you handle a coworker who takes credit for your work?",
        "What would you do if you strongly disagreed with a company policy?",
        "How would you approach leading a project in a domain you know little about?",
        "What would you do if a tight deadline conflicted with code quality standards?",
        "How would you handle a customer escalation that reaches your team?",
        "What would you do if a key team member left mid-project?",
        "How would you handle discovering a security vulnerability in production?",
        "What would you do if asked to implement a feature you believe is wrong?",
    ],
}


def get_random_topic() -> dict:
    """Return a random topic from a random category."""
    category = random.choice(list(TOPICS.keys()))
    topic = random.choice(TOPICS[category])
    return {"category": category, "topic": topic}


def get_topic_by_category(category: str) -> dict:
    """Return a random topic from a specific category."""
    if category not in TOPICS:
        raise ValueError(f"Unknown category: {category}. Available: {list(TOPICS.keys())}")
    topic = random.choice(TOPICS[category])
    return {"category": category, "topic": topic}


def get_all_categories() -> list:
    """Return list of available categories."""
    return list(TOPICS.keys())
